import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const source = readFileSync(new URL('../lib/chat.js', import.meta.url), 'utf8')
const { chatTurns } = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'))
const logs = (...text) => text.map((text, i) => ({ text, level: 'INFO', at: i + 1 }))
let turns = chatTurns(logs('Writing components/CheckoutClient.jsx', 'written components/CheckoutClient.jsx (40 lines)', 'Editing components/CheckoutClient.jsx', 'patched components/CheckoutClient.jsx (41 lines)'))
assert.equal(turns.length, 2)
assert.equal(turns.filter(turn => turn.inProgress).length, 0)
assert.deepEqual(turns.map(turn => turn.action), ['written', 'patched'])
turns = chatTurns(logs('Writing components/A.jsx', 'Reading app/page.jsx', 'Writing components/A.jsx', 'written components/A.jsx (10 lines)'))
assert.equal(turns.filter(turn => turn.kind === 'write').length, 1)
turns = chatTurns(logs('Writing ./components/A.jsx', 'Writing components/B.jsx', 'Reading app/page.jsx', 'written components/A.jsx (10 lines)', 'written components/B.jsx (12 lines)'))
assert.equal(turns.filter(turn => turn.kind === 'write').length, 2)
assert.equal(turns.filter(turn => turn.inProgress).length, 0)
turns = chatTurns(logs('Writing components/Foo.jsx', 'written components/foo.jsx (1 lines)'))
assert.equal(turns.filter(turn => turn.inProgress).length, 1, 'Different case-sensitive files must not be merged')
console.log('File activity: starts superseded by completions; independent edits and distinct paths retained')
